services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - teatro-vol:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ["--auth"]

  mongo-express:
    container_name: mongo-express
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
    ports:
      - 8081:8081
    restart: always

  api-teatro:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
      # depends_on: 
      #   - db
      #   - mongo-express

  # volumes:
  #   - .:/app/
  #   - /app/node_modules
    container_name: apiControlTeatro
    ports:
      - 3003:3003

volumes:
  teatro-vol:
    driver: local
    
  # api-controlTeatro:
  #   container_name: apiControlTeatro
  #   image: pleslysarahi/teatro:rosa
  #   depends_on: 
  #     - db
  #     - mongo-express
  #   ports:
  #     - 3002:3002

